apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: website
  annotations:
    crossplane.io/external-name: website
spec:
  forProvider:
    source: Remote
    module: "git::https://github.com/PierreStephaneVoltaire/static-site-s3.git?ref=main"
    vars:
    - key: domain_name
      value: psvoltaire.ca
    env:
    - name:  AWS_REGION
      value: 'us-east-1'
    
  writeConnectionSecretToRef:
    namespace:  crossplane-system
    name: terraform-workspace-website
  providerConfigRef:
    name: aws-ca-central-1