apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: website
  annotations:
    crossplane.io/external-name: website
spec:
  forProvider:
    source: Remote
    module: https://github.com/PierreStephaneVoltaire/static-site-s3
    vars:
    - key: domain_name
      value: psvoltaire.ca
  writeConnectionSecretToRef:
    namespace: default
    name: terraform-workspace-website
  providerConfigRef:
    name: aws-ca-central-1